baseurl = "http://blog.rogermolas.com"
title = "Roger Molas"
theme = "temple"
publishDir = "docs"
copyright = "(c) 2017 - 2018 Roger Molas -- All rights reserved."

[params]
  # Enables syntax highlighting
  highlight = true 
  hjslangs = ["go", "vim", "swift", "objc-C", "ruby", "python"]
  topmenu = "PROJECTS"

# Builds a list page for each category given
[taxonomies]
  tag = "PROJECTS"
  category = "categories"

[author]
  name = "Roger Molas"
  github = "rogermolas"
  email = "contact@rogermolas.com"
  twitter = "roger_molas"
