baseurl = "https://rogermolas.github.io/blogsite/"
DefaultContentLanguage = "en"
publishDir = "docs"
title = "Roger Molas"
theme = "beautifulhugo"
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true
[params]
    useChroma = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Welcome to my site and this is the place where i collect my thoughts, works and findings to share with the public. "
  logo = "img/profile.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true

[Author]
  name = "Roger Molas"
  email = "contact@rogermolas.com"
  github = "rogermolas"
  twitter = "roger_molas"
  linkedin = "rogermolas"
  stackoverflow = "/users/592526/roger"

[[menu.main]]
    name = "ABOUT"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "PROJECTS"
    url = ""
    weight = 2

[[menu.main]]
    name = "BLOG"
    url = ""
    weight = 1


